### ISSUE TITLE
Pull Request for Specific Files

### ISSUE THREAD

**Issue by devashish2019** [jdebacker/CompEcon_Fall19#37]
Hi Jason,

I am trying to upload the 3-period OG problem we did in the class to build the PS9 solution.

I have created a PS9 branch on my local repo. But I am unable to limit the pull request to the specific folder that has the OG models, everything seems to be pulled together. Could you please advise.

Thanks
Devashish

**Comment by jdebacker** [comment]
@devashish2019 If you figured this out, would you mind posting what you did hear for others' benefit?  Thanks!

**Comment by devashish2019** [comment]
Hi @jdebacker , I though I did through this link:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/filtering-files-in-a-pull-request

But I do not see any "file filter" when I make the pull request. Please advise.

Thanks

**Comment by jdebacker** [comment]
A couple questions to help me figure out what's going on:

1. When you are adding a file to be tracked by git are you adding each individually?  e.g., `git add filename.py` or you are you adding everything at once?  e.g., `git add *`?  You want to do the former.

2. What are the other files that are being added that you don't want?  Are they the files associated with problem sets that you had committed to your `master` branch?

**Comment by devashish2019** [comment]
1. I am adding files individually
2. Yes, when I see the list of files after opening a pull request, it shows all my problem set solutions that were committed to my master branch

**Comment by jdebacker** [comment]
@devashish2019 Ok - thanks for these answers.  I was worried this might be an issue. 

Hold tight and I'll have a different suggestion for how you all can collaborate on GitHub tomorrow.

**Comment by devashish2019** [comment]
Thanks so much!

**Comment by jdebacker** [comment]
@devashish2019 et al:

Since I had you all commit your problem sets to your `master` branch, there's no way for you to checkout another branch from that and not add those files to the class repo.  

What we're going to do is work in a new repo set up just for PS9.  You can find that repo here: https://github.com/jdebacker/ProblemSet9

To fork, clone, and configure this repo, look back at our git instructions [here](https://github.com/jdebacker/CompEcon_Fall19/tree/master/Productivity).  The first 6 steps to take are the following:
1. Go to https://github.com/jdebacker/ProblemSet9 and click the "Fork" button.
2. On your newly created fork, click on the "Clone or download" button and copy that url.
3. In a terminal window (or Anaconda command prompt on Windows), navigate to the file directory where you want to put this new repo (but don't create a `ProblemSet9` folder - this will be created when you clone the repo) and type `git clone the_url_you_copied`.  This url will be different for each of you because it will point to *your* fork.
3. Type `cd ProblemSet9`
4. Type `git remote -v`.  You should see fetch and push with urls pointing towards your fork.  You will need to add the url to find my repo.
5. Type `git remote add upstream https://github.com/jdebacker/ProblemSet9.git` (the url here will be the same for you all since you will point to my repo).

You are now ready to go!

From this point onwards you'll want to:
1) Checkout a new branch (`git checkout -b branch_name`) when you are starting new edits to files.
2) When you are ready to add changes to a file you edited, do `git add filename` and then `git commit -m "a note about what you did"` (you can feel free to `git add` multiple files before committing, just add one file per `add` command and don't use wildcards that will include files you might now want to add).
3) Push these changes to your remote repo: `git push origin name_of_branch`
4) Continue to sync your branches with the latest changes in the upstream repository.  Do this with the following:
  * `git fetch upstream`
  * `git merge upstream/master`
  *  `git push origin name_of_branch_you_are_on`
4) When you've made and committed and push all the changes that you'd like to from a given branch, open a pull request to the upstream repo (i.e., https://github.com/jdebacker/ProblemSet9).  Do this by going to your fork in a web browser.  You'll see a button for opening a pull request.  Click that and then follow the steps, which should be straight-forward.  Don't be shy about providing info.  We all want to know what good code you've added, so describe it a bit.
